### ISSUE TITLE
Cannot start the Flutter App

### ISSUE THREAD

**Issue by Arka2009** [MirServer/iot-example-graphical-snap#13]
I am trying to deploy the Flutter App on a Raspberry-Pi 4B running Ubuntu 22.04.1 LTS. I was able to build the snap successfully, but whenever I try to launch I encounter the following problem
```bash
amaity@pi-ubuntu3:~/Desktop/iot-example-graphical-snap$ snap run iot-example-graphical-snap
inotifywait: unrecognized option '--include'
inotifywait: unrecognized option '--include'
inotifywait: unrecognized option '--include'
inotifywait: unrecognized option '--include'
inotifywait: unrecognized option '--include'
^C
amaity@pi-ubuntu3:~/Desktop/iot-example-graphical-snap$
``` 

I think the wayland-launch script enters the infinite loop and I have to terminate the process. Also the itonifywait, complains about the unrecognized option. However, when I run with sudo, the itonifywait error message dissappears, but it still hangs and nothing is displayed on the screen.

**Comment by AlanGriffiths** [comment]
The reason for the loop is that the snap is waiting for the Wayland server (Ubuntu Frame) to start.

Are you following [the tutorial](https://mir-server.io/docs/packaging-a-flutter-application-as-an-iot-gui)? If so, you should have Ubuntu Frame running in a window. If you closed it by mistake, open it again:

    ubuntu-frame&

**Comment by Arka2009** [comment]
Thank you. I missed this step. It works now.
