### ISSUE TITLE
GTK 3.0 Bug

### ISSUE THREAD

**Issue by rickypid** [MirServer/iot-example-graphical-snap#2]
Hi,

i have the issue described here https://github.com/flutter/flutter/issues/76383

The solution is upgrade GTK from 3.0 to 3.24. (https://github.com/flutter/flutter/issues/76383#issuecomment-798438786)

https://github.com/MirServer/iot-example-graphical-snap/blob/bc3a71846272e54bdcbcd5ef4d2750f8f63706ee/snap/snapcraft.yaml#L73

**Comment by AlanGriffiths** [comment]
Ubuntu 20.04 (on whuch core20 is based) has GTK 3.24 already.

```
$ dpkg -S /etc/gtk-3.0/im-multipress.conf 
libgtk-3-common: /etc/gtk-3.0/im-multipress.conf
$ apt policy libgtk-3-common
libgtk-3-common:
  Installed: 3.24.20-0ubuntu1.1
  Candidate: 3.24.20-0ubuntu1.1
  Version table:
 *** 3.24.20-0ubuntu1.1 500
        500 http://gb.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
        500 http://gb.archive.ubuntu.com/ubuntu focal-updates/main i386 Packages
        100 /var/lib/dpkg/status
     3.24.18-1ubuntu1 500
        500 http://gb.archive.ubuntu.com/ubuntu focal/main amd64 Packages
        500 http://gb.archive.ubuntu.com/ubuntu focal/main i386 Packages
```

**Comment by rickypid** [comment]
Thanks @AlanGriffiths ,

I have build the snap in CI on Ubuntu 20.04 server machine on Google Cloud. 
By default has not installed, now i have installed them. 

Tommorw i try install a new updated snap. 

are other dependencies necessary to build snap on Ubuntu server?

**Comment by AlanGriffiths** [comment]
> are other dependencies necessary to build snap on Ubuntu server?

@rickypid all the branches of this project are `base: core20` and, as a result, those that use GTK will use GTK-3.24.20. So your original "solution" is already in place.

You should be able to checkout any of these branches and package using `snapcraft` on most versions of Linux (including Ubuntu Server). If you have problems using `snapcraft` look on [the appropriate forum](https://forum.snapcraft.io/c/snapcraft/13).
