### ISSUE TITLE
WaylandWindowDecorations flag makes touch stop working

### ISSUE THREAD

**Issue by jdbelo** [MirServer/iot-example-graphical-snap#5]
After some tests, I found out the WaylandWindowDecorations flag was preventing the touch to work. 
So I made a little change to this repo (Electron-quick-start branch). In a nutshell, I removed WaylandWindowDecorations from --enable-features in order to make the multitouch work (I don't exactly know why, just trial and error). Otherwise, the touch doesn't work at all (neither basic gestures such as tap, double-tap, scroll ...).

Has anyone faced the same problem?

**Comment by AlanGriffiths** [comment]
To clarify, "touch stop working" is about the specific "pinch/zoom" gesture we've been discussing in https://github.com/MirServer/mir/issues/2463? (And not all touch)

**Comment by frank-dspeed** [comment]
@jdbelo i hope you did follow my advice to only set the ozone hint flag and leave all the other wayland flags untouched simply do never use them they get all deprecated

**Comment by bugraaydogar** [comment]
Hi @jdbelo,

I made a quick test by using (quick-start-electron) as well as WPE WebKit for Mir Kiosk.
**Environment:** Ubuntu Core 20 with Rpi4 (8 GB) + Touch Screen (https://www.raspberrypi.com/products/raspberry-pi-touch-display/)
**Modifications:** I had to enable `WaylandWindowDecorations` since it was removed by using `--enable-features=UseOzonePlatform, WaylandWindowDecorations`. Also, I added `--disable-gpu` to be able to run on Rpi4 since it can not use GPU acceleration on Electron yet.

**Results:**
- Touch was working fine with `WaylandWindowDecorations`. I have not realize any issue. But, I have not test zoom-in/out gesture yet.
- There was no issues observed with  WPE WebKit for Mir Kiosk. It was possible to zoom-in/out when using google maps. However, I realized that some websites does not process/allow zoom-in/out gestures. So, it looks to me that it is directly application specific.

I will edit this post and update it when I test zoom-in/out gestures while using Electron.

Thanks,
Bugra

**Comment by jdbelo** [comment]
Quick update regarding this issue:

- As I reported when I opened the issue, WaylandWindowDecorations was preventing the touch to work. All gestures were being affected. However, after the @bugraaydogar comment, I realized there was missing a space after the comma (it was `--enable-features=UseOzonePlatform,WaylandWindowDecorations` instead of -`-enable-features=UseOzonePlatform, WaylandWindowDecorations`). After making this change the touch started to work again. So the problem was not related to `WaylandWindowDecorations`. (Note: as expected this change doesn't change [the issues related to the pinch/zoom-in gesture](https://github.com/MirServer/mir/issues/2463))

- @frank-dspeed I hadn't followed yet your suggestions (I'm sorry). I had only made some needed minor changes to avoid comparing uncomparable scenarios. But, In the meantime, I managed to perform some tests following your tip, but I didn't manage to make it work. Have you tested it? The application was never launched in the ubuntu-frame. I tried the three combinations below.

  ```
  exec $SNAP/electron-helloworld/electron-quick-start \
	  --ozone-platform-hint=auto \
	  --no-sandbox
  ```

  ```
  exec $SNAP/electron-helloworld/electron-quick-start \
	  --enable-features=UseOzonePlatform \
	  --ozone-platform-hint=auto \
	  --no-sandbox
  ```

  ```
  exec $SNAP/electron-helloworld/electron-quick-start \
	  --enable-features=UseOzonePlatform \
	  --ozone-platform-hint=wayland \
	  --no-sandbox
  ```

**Comment by AlanGriffiths** [comment]
> * So the problem was not related to `WaylandWindowDecorations`

OK, thanks. Closing the issue

> * I realized that some websites does not process/allow zoom-in/out gestures. So, it looks to me that it is directly application specific

That also makes sense, thanks for looking into this

**Comment by frank-dspeed** [comment]
@jdbelo please post the logs of your tests as that is valueable information that means chromium upstream has a problem detecting the wayland support

**Comment by AlanGriffiths** [comment]
@jdbelo you will need `--disable-dev-shm-usage` to share buffers from snap confinement

**Comment by jdbelo** [comment]
@frank-dspeed The log is the always the same: 

```
snap logs -f iot-example-graphical-snap
2022-07-06T14:39:04Z systemd[1]: Started Service for snap application iot-example-graphical-snap.iot-example-graphical-snap.
2022-07-06T14:39:05Z iot-example-graphical-snap.iot-example-graphical-snap[12781]: [12781:0706/143905.029549:ERROR:ozone_platform_x11.cc(248)] Missing X server or $DISPLAY
2022-07-06T14:39:05Z iot-example-graphical-snap.iot-example-graphical-snap[12781]: [12781:0706/143905.029571:ERROR:env.cc(226)] The platform failed to initialize.  Exiting.
2022-07-06T14:39:05Z systemd[1]: snap.iot-example-graphical-snap.iot-example-graphical-snap.service: Main process exited, code=exited, status=139/n/a
2022-07-06T14:39:05Z systemd[1]: snap.iot-example-graphical-snap.iot-example-graphical-snap.service: Failed with result 'exit-code'.
2022-07-06T14:39:05Z systemd[1]: snap.iot-example-graphical-snap.iot-example-graphical-snap.service: Scheduled restart job, restart counter is at 3.
2022-07-06T14:39:05Z systemd[1]: Stopped Service for snap application iot-example-graphical-snap.iot-example-graphical-snap.
2022-07-06T14:39:05Z systemd[1]: snap.iot-example-graphical-snap.iot-example-graphical-snap.service: Start request repeated too quickly.
2022-07-06T14:39:05Z systemd[1]: snap.iot-example-graphical-snap.iot-example-graphical-snap.service: Failed with result 'exit-code'.
2022-07-06T14:39:05Z systemd[1]: Failed to start Service for snap application iot-example-graphical-snap.iot-example-graphical-snap.
```

@AlanGriffiths I've followed your suggestion and I've also tried:

```
exec $SNAP/electron-helloworld/electron-quick-start \
	--ozone-platform-hint=auto \
	--disable-dev-shm-usage \
        --no-sandbox
```

```
exec $SNAP/electron-helloworld/electron-quick-start \
	--enable-features=UseOzonePlatform, WaylandWindowDecorations \
	--ozone-platform-hint=auto \
	--disable-dev-shm-usage \
        --no-sandbox
```

The log is exactly the same (☝️) and nothing has changed (the electron app continues not being not launched).

**Comment by AlanGriffiths** [comment]
@jdbelo if anyone else has this problem, they are unlikely to look under "WaylandWindowDecorations flag makes touch stop working".

> 2022-07-06T14:39:05Z iot-example-graphical-snap.iot-example-graphical-snap[12781]: [12781:0706/143905.029549:ERROR:ozone_platform_x11.cc(248)] Missing X server or $DISPLAY
> 2022-07-06T14:39:05Z iot-example-graphical-snap.iot-example-graphical-snap[12781]: [12781:0706/143905.029571:ERROR:env.cc(226)] The platform failed to initialize.  Exiting.

But if you read the above messages, you'll see that Ozone fails to connect to an X server. Which is not surprising as /1/ the snap does not connect the `x11` interface; and /2/ there is no `x11` slot provided on Ubuntu Core.
