### ISSUE TITLE
 Electron App doesn’t show sometimes.(5% of time when turning on device)

### ISSUE THREAD

**Issue by crashedapp** [MirServer/iot-example-graphical-snap#9]
I’m running the electron example on an Intel NUC on Ubuntu Server 22.04.1 LTS.
This setup works very well most of the time. I occasionally have an issue where the electron app doesn’t appear and all I see on the screen is the gray display of Ubuntu frame.
It happens about 1 out of 20 times I boot the device.

When I inspect the snap daemon service for the Electron app it says it’s active and running. The only way I have found to remedy the situation is to restart the service for the electron snap.  Then the electron app will appear. I assume this is somehow timing related.

As it doesn’t happen all the time (which is very peculiar) I would like to have my own Kiosk watchdog service inspect the electron app inside of the container of the snap or some how detect that nothing is connected to Ubuntu Frame?

Any tips or advice would be much appreciated. I Was hoping just looking at the snap service status of the electron app was enough but since it says active and running I need something that digs deeper.

**Comment by Saviq** [comment]
Hi @crashedapp, when you encounter the broken app, do you see the process running? Are there any logs in `snap logs <your snap>` that suggest what went wrong?

**Comment by crashedapp** [comment]
@Saviq  thanks for the suggestions.
I've dumped the commands below.

I finally got the kiosk to  show only  the Ubuntu Frame gray screen again. -Took about 60 reboots this time. 
I left the app in its current state in case there are any other things someone thinks  I should look at.
Based on the logs from my electron app (rse-kioskshell-snap) it appears to be running normally - just no output to the screen.

I believe the first two messages from snap logs about "gpu_init.cc" and "Kernel has no file descriptor" occur even when everything is working.

Any additional suggestions would be appreciated.


### rse@rsedevice:~$ systemctl status snap.rse-kioskshell-snap.rse-kioskshell-snap.service

● snap.rse-kioskshell-snap.rse-kioskshell-snap.service - Service for snap application rse-kioskshell-snap.rse-kioskshell-snap
     Loaded: loaded (/etc/systemd/system/snap.rse-kioskshell-snap.rse-kioskshell-snap.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2022-11-29 00:37:14 UTC; 17min ago
   Main PID: 1117 (wayland-launch)
      Tasks: 2 (limit: 4355)
     Memory: 36.0M
        CPU: 4.104s
     CGroup: /system.slice/snap.rse-kioskshell-snap.rse-kioskshell-snap.service
             ├─1117 /bin/sh /snap/rse-kioskshell-snap/x1/bin/wayland-launch /snap/rse-kioskshell-snap/x1/bin/dbus-launch /snap/rse-kioskshell-snap/x1/usr/bin/wrapper
             └─1536 inotifywait --event create /run/user/0

Nov 29 00:37:14 rsedevice systemd[1]: Started Service for snap application rse-kioskshell-snap.rse-kioskshell-snap.
Nov 29 00:37:31 rsedevice rse-kioskshell-snap.rse-kioskshell-snap[1525]: Setting up watches.
Nov 29 00:37:31 rsedevice rse-kioskshell-snap.rse-kioskshell-snap[1525]: Watches established.
Nov 29 00:37:32 rsedevice rse-kioskshell-snap.rse-kioskshell-snap[1525]: /run/user/0/ CREATE wayland-0.lock
Nov 29 00:37:32 rsedevice rse-kioskshell-snap.rse-kioskshell-snap[1536]: Setting up watches.
Nov 29 00:37:32 rsedevice rse-kioskshell-snap.rse-kioskshell-snap[1536]: Watches established.



### rse@rsedevice:~$ sudo snap logs rse-kioskshell-snap

2022-11-29T00:33:55Z rse-kioskshell-snap.rse-kioskshell-snap[1574]: [1574:1129/003355.976349:ERROR:gpu_init.cc(521)] Passthrough is not supported, GL is egl, ANGLE is
2022-11-29T00:33:56Z rse-kioskshell-snap.rse-kioskshell-snap[1574]: WARNING: Kernel has no file descriptor comparison support: Operation not permitted
2022-11-29T00:33:56Z rse-kioskshell-snap.rse-kioskshell-snap[1543]: mainWindow navigated to:file:///snap/rse-kioskshell-snap/x1/rse-kioskshell-packer/resources/app/app/mainWindow/screensaver.html
2022-11-29T00:33:56Z rse-kioskshell-snap.rse-kioskshell-snap[1543]: Cleared Application Cache
2022-11-29T00:37:14Z systemd[1]: Started Service for snap application rse-kioskshell-snap.rse-kioskshell-snap.
2022-11-29T00:37:31Z rse-kioskshell-snap.rse-kioskshell-snap[1525]: Setting up watches.
2022-11-29T00:37:31Z rse-kioskshell-snap.rse-kioskshell-snap[1525]: Watches established.
2022-11-29T00:37:32Z rse-kioskshell-snap.rse-kioskshell-snap[1525]: /run/user/0/ CREATE wayland-0.lock
2022-11-29T00:37:32Z rse-kioskshell-snap.rse-kioskshell-snap[1536]: Setting up watches.
2022-11-29T00:37:32Z rse-kioskshell-snap.rse-kioskshell-snap[1536]: Watches established.



### rse@rsedevice:~$ sudo snap services

Service                                  Startup  Current   Notes
lxd.activate                             enabled  inactive  -
lxd.daemon                               enabled  inactive  socket-activated
lxd.user-daemon                          enabled  inactive  socket-activated
rse-kioskshell-snap.rse-kioskshell-snap  enabled  active    -
ubuntu-frame.daemon                      enabled  active    -




### rse@rsedevice:~$ sudo snap logs ubuntu-frame

2022-11-29T00:37:32Z ubuntu-frame.daemon[1118]: [2022-11-29 00:37:32.520387] <information> mirserver: . |_ EDID manufacturer: DWE
2022-11-29T00:37:32Z ubuntu-frame.daemon[1118]: [2022-11-29 00:37:32.520635] <information> mirserver: . |_ EDID product code: 8448
2022-11-29T00:37:32Z ubuntu-frame.daemon[1118]: [2022-11-29 00:37:32.520874] <information> mirserver: . |_ Physical size 21.1" 470x260mm
2022-11-29T00:37:32Z ubuntu-frame.daemon[1118]: [2022-11-29 00:37:32.521088] <information> mirserver: . |_ Power is on
2022-11-29T00:37:32Z ubuntu-frame.daemon[1118]: [2022-11-29 00:37:32.521275] <information> mirserver: . |_ Current mode 1024x600 59.82Hz
2022-11-29T00:37:32Z ubuntu-frame.daemon[1118]: [2022-11-29 00:37:32.521479] <information> mirserver: . |_ Preferred mode 1024x600 59.82Hz
2022-11-29T00:37:32Z ubuntu-frame.daemon[1118]: [2022-11-29 00:37:32.521681] <information> mirserver: . |_ Orientation normal
2022-11-29T00:37:32Z ubuntu-frame.daemon[1118]: [2022-11-29 00:37:32.521877] <information> mirserver: . |_ Logical size 1024x600
2022-11-29T00:37:32Z ubuntu-frame.daemon[1118]: [2022-11-29 00:37:32.522095] <information> mirserver: . |_ Logical position +0+0
2022-11-29T00:37:32Z ubuntu-frame.daemon[1118]: [2022-11-29 00:37:32.522284] <information> mirserver: . |_ Scaling factor: 1.00

**Comment by Saviq** [comment]
@crashedapp nope, your app is not running, because of this still waiting for the socket to show up:
```plain
 └─1536 inotifywait --event create /run/user/0
```

Despite the inotify actually firing:
```plain
 /run/user/0/ CREATE wayland-0.lock
```

This is coming from here:

https://github.com/MirServer/iot-example-graphical-snap/blob/da3abddd3b42b58c95f9cac55894f95560a90243/wayland-launch/bin/wayland-launch#L19-L29

Looks like there is a race between the socket showing up and `inotifywait` realising it's created. A trivial workaround would be adding a [`--timeout 5`](https://linux.die.net/man/1/inotifywait) or so to the `inotifywait` command so it doesn't wait indefinitely in this case.

**Comment by AlanGriffiths** [comment]
> Looks like there is a race between the socket showing up and `inotifywait` realising it's created

I agree that the script is waiting on the socket. But the race is slightly different to that:

1. inotify sees the creation `/run/user/0/ CREATE wayland-0.lock` and exits
2. We restart the look and ` [ -O "$1" ]` fails
3. We wait on a second instance of `inotifywait` which (obviously) doesn't see a second create.

That is, the file is created, but can't be opened,

**Comment by AlanGriffiths** [comment]
@crashedapp I have difficulty reproducing the problem you see, but it is clear from the logs what is happening.

1. What is the device you are using?
2. As you can reproduce, could you try this version of the above function:

```bash
wait_for()
{
  until 
    until
      inotifywait --event create "$(dirname "$1")"&
      inotify_pid=$!
      [ -e "$1" ]
    do
      wait "${inotify_pid}"
    done
    kill "${inotify_pid}"
    [ -O "$1" ]
  do    
    sleep 1 
  done
}
```
This ought to deal with the race you are seeing

**Comment by crashedapp** [comment]
@AlanGriffiths @Saviq  
I applied the fix#10. Unfortunately it doesn't seem to have helped. I did a snapcraft clean and then rebuilt my snap and installed. I'm getting the same issue where I only see the ubuntu frame gray screen. This time it took about 15 reboots for it to happen .
I don't know if it matters but it seems the issue is more likely to happen when the device is not connected to any network.
The device is an Intel NUC 8 Chaco Canyon Rugged in which I have several and all experience the same issue. 

Here are my latest results from the service status:

### rse@rsedevice:~$ systemctl status snap.rse-kioskshell-snap.rse-kioskshell-snap.service
● snap.rse-kioskshell-snap.rse-kioskshell-snap.service - Service for snap application rse-kioskshell-snap.rse-kioskshell-snap
     Loaded: loaded (/etc/systemd/system/snap.rse-kioskshell-snap.rse-kioskshell-snap.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-11-30 09:46:53 UTC; **15min ago**
   Main PID: 1157 (wayland-launch)
      Tasks: 2 (limit: 4355)
     Memory: 33.5M
        CPU: 3.275s
     CGroup: /system.slice/snap.rse-kioskshell-snap.rse-kioskshell-snap.service
             ├─1157 /bin/sh /snap/rse-kioskshell-snap/x1/bin/wayland-launch /snap/rse-kioskshell-snap/x1/bin/dbus-launch /snap/rse-kioskshell-snap/x1/usr/bin/wrapper
             └─1598 inotifywait --event create /run/user/0

Nov 30 09:46:53 rsedevice systemd[1]: Started Service for snap application rse-kioskshell-snap.rse-kioskshell-snap.
Nov 30 09:47:10 rsedevice rse-kioskshell-snap.rse-kioskshell-snap[1587]: Setting up watches.
Nov 30 09:47:10 rsedevice rse-kioskshell-snap.rse-kioskshell-snap[1587]: Watches established.
Nov 30 09:47:11 rsedevice rse-kioskshell-snap.rse-kioskshell-snap[1587]: /run/user/0/ CREATE wayland-0.lock
Nov 30 09:47:11 rsedevice rse-kioskshell-snap.rse-kioskshell-snap[1598]: Setting up watches.
Nov 30 09:47:11 rsedevice rse-kioskshell-snap.rse-kioskshell-snap[1598]: Watches established.


And here is the same log again 10 minutes later.

### rse@rsedevice:~$ systemctl status snap.rse-kioskshell-snap.rse-kioskshell-snap.service
● snap.rse-kioskshell-snap.rse-kioskshell-snap.service - Service for snap application rse-kioskshell-snap.rse-kioskshell-snap
     Loaded: loaded (/etc/systemd/system/snap.rse-kioskshell-snap.rse-kioskshell-snap.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-11-30 09:46:53 UTC; **25min ago**
   Main PID: 1157 (wayland-launch)
      Tasks: 2 (limit: 4355)
     Memory: 33.5M
        CPU: 3.275s
     CGroup: /system.slice/snap.rse-kioskshell-snap.rse-kioskshell-snap.service
             ├─1157 /bin/sh /snap/rse-kioskshell-snap/x1/bin/wayland-launch /snap/rse-kioskshell-snap/x1/bin/dbus-launch /snap/rse-kioskshell-snap/x1/usr/bin/wrapper
             └─1598 inotifywait --event create /run/user/0

Nov 30 09:46:53 rsedevice systemd[1]: Started Service for snap application rse-kioskshell-snap.rse-kioskshell-snap.
Nov 30 09:47:10 rsedevice rse-kioskshell-snap.rse-kioskshell-snap[1587]: Setting up watches.
Nov 30 09:47:10 rsedevice rse-kioskshell-snap.rse-kioskshell-snap[1587]: Watches established.
Nov 30 09:47:11 rsedevice rse-kioskshell-snap.rse-kioskshell-snap[1587]: /run/user/0/ CREATE wayland-0.lock
Nov 30 09:47:11 rsedevice rse-kioskshell-snap.rse-kioskshell-snap[1598]: Setting up watches.
Nov 30 09:47:11 rsedevice rse-kioskshell-snap.rse-kioskshell-snap[1598]: Watches established.

**Comment by crashedapp** [comment]
@AlanGriffiths 
Here is the wayland-launch 

### rse@rsedevice:/snap/rse-kioskshell-snap/current/bin$ cat wayland-launch

```sh
#!/bin/sh
set -e

for PLUG in opengl wayland graphics-core20; do
  if ! snapctl is-connected ${PLUG}
  then
    echo "WARNING: ${PLUG} interface not connected! Please run: /snap/${SNAP_INSTANCE_NAME}/current/bin/setup.sh"
  fi
done

if ! command -v inotifywait > /dev/null
then
    echo "ERROR: inotifywait could not be found, mir-kiosk-snap-launch expects:"
    echo " . . :     stage-packages:"
    echo " . . :        - inotify-tools"
    exit 1
fi

wait_for()
{
  until
    until
      inotifywait --event create "$(dirname "$1")"&
      inotify_pid=$!
      [ -e "$1" ]
    do
      wait "${inotify_pid}"
    done
    kill "${inotify_pid}"
    [ -O "$1" ]
  do
    sleep 1
  done
}

real_xdg_runtime_dir=$(dirname "${XDG_RUNTIME_DIR}")
real_wayland=${real_xdg_runtime_dir}/${WAYLAND_DISPLAY:-wayland-0}

# On core systems may need to wait for real XDG_RUNTIME_DIR
wait_for "${real_xdg_runtime_dir}"
wait_for "${real_wayland}"

mkdir -p "$XDG_RUNTIME_DIR" -m 700
ln -sf "${real_wayland}" "$XDG_RUNTIME_DIR"
ln -sf "${real_wayland}.lock" "$XDG_RUNTIME_DIR"
unset DISPLAY
```

**Comment by AlanGriffiths** [comment]
@crashedapp thanks for confirming.

I'm still thinking about the right way to solve this. But here are two that may, in practice, solve the problem for you:

1.
```bash
wait_for()
{
  until
    until
      inotifywait --event create "$(dirname "$1")" --include "$(basename "$1")"&
      inotify_pid=$!
      [ -e "$1" ]
    do
      wait "${inotify_pid}"
    done
    kill "${inotify_pid}"
    [ -O "$1" ]
  do
    sleep 1
  done
}
```

2.
```bash
wait_for()
{
  until
    until
      inotifywait --event create "$(dirname "$1")" --timeout 5"&
      inotify_pid=$!
      [ -e "$1" ]
    do
      wait "${inotify_pid}"
    done
    kill "${inotify_pid}"
    [ -O "$1" ]
  do
    sleep 1
  done
}
```

**Comment by crashedapp** [comment]
@AlanGriffiths 
Can I just edit the wayland-launch file in /snap/rse-kioskshell-snap/current/bin to try these fixes or do I need to rebuild and install the snap again?

**Comment by AlanGriffiths** [comment]
> Can I just edit the wayland-launch file in /snap/rse-kioskshell-snap/current/bin

Not quite, that's a "ro" filesystem. But morally the same thing is described here:

https://snapcraft.io/docs/snap-try

**Comment by crashedapp** [comment]
I added a check in my watchdog service to count the number of tasks reported by systemctl status for my snap service. I noticed the hang condition is when there are 2 or less tasks reported (As seen in my dump above) whereas when everything running there is 10+ tasks running.

This is working well now for my use as its catching the problem and restarting the snap service as needed though purely a workaround for now. I'm fairly confident the condition for this to happen is more likely to happen when the device has no ethernet connected but have no explanation on why that would be.

I'm not sure which of the 2 proposed solutions posted above to try so the condition doesn't appear in the first place. I'm happy to test if one is favored over the other.

**Comment by AlanGriffiths** [comment]
@crashedapp if you could perhaps try this version:

```bash
wait_for()
{
  until
    until
      inotifywait --event create "$(dirname "$1")" --include "$(basename "$1")"&
      inotify_pid=$!
      [ -e "$1" ] || sleep 2 && [ -e "$1" ]
    do
      wait "${inotify_pid}"
    done
    kill "${inotify_pid}"
    [ -O "$1" ]
  do
    sleep 1
  done
}
```

**Comment by crashedapp** [comment]
@AlanGriffiths 
I tried your latest version.  I have done 100 reboots of the device and it looks like the issue is now resolved as I no longer see the issue.
Thanks for working to resolve this issue so quickly.

**Comment by AlanGriffiths** [comment]
@crashedapp thank you for bringing this to our attention and working with us confirm the resolution
